---
version: '3.6'




x-quorum-def:
  &quorum-def
  restart: "on-failure"
  build:
    context: config/goquorum
    args:
      QUORUM_VERSION: ${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s



x-tessera-def:
  &tessera-def
  # build:
  #   context: config/tessera
  #   args:
  #     TESSERA_VERSION: ${TESSERA_VERSION:-latest}
  image: consensys/tessera:${TESSERA_VERSION:-latest}
  restart: "on-failure"
  environment:
    TESSERA_MODE: tessera
  expose:
    - 9000
    - 9080
    - 9101
  healthcheck:
    # test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    test: ["CMD", "wget", "--spider", "--no-proxy", "http://localhost:9000/upcheck"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s


services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.11
    volumes:
      - ./config/nodes/validator1:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.12
    volumes:
      - ./config/nodes/validator2:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.13
    volumes:
      - ./config/nodes/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.14
    volumes:
      # a:b => a目錄掛載到容器內的b
      - ./config/nodes/validator4:/config/keys # 與這個路徑對應
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys # make sure this matches the volume path
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode: # provides public RPC interface for the network
    << : *quorum-def
    container_name: rpcnode
    user: root
    ports:
      - 8545:8545/tcp # JSON-RPC
      - 8546:8546/tcp # websocket
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.15
    volumes:
      - ./config/nodes/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,admin
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15
      shared-net: {}


  # Tessera nodes for private transactions
  # Each member has its own Tessera node and Quorum node
  member1tessera:
    << : *tessera-def
    platform: linux/amd64
    ports:
      - 9081:9080
    volumes:
      - ./config/nodes/member1:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.26

  member1quorum:
    << : *quorum-def
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member1tessera
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=enhanced
      - QUORUM_PTM=member1tessera
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.16
    volumes:
      - ./config/nodes/member1:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  member2tessera:
    << : *tessera-def
    platform: linux/amd64
    ports:
      - 9082:9080
    volumes:
      - ./config/nodes/member2:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.27

  member2quorum:
    << : *quorum-def
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member2tessera
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=enhanced
      - QUORUM_PTM=member2tessera
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.17
    volumes:
      - ./config/nodes/member2:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  member3tessera:
    << : *tessera-def
    platform: linux/amd64
    ports:
      - 9083:9080
    volumes:
      - ./config/nodes/member3:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.28

  member3quorum:
    << : *quorum-def
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member3tessera
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=enhanced
      - QUORUM_PTM=member3tessera
      - ADDITIONAL_ARGS=--nat=extip:172.16.239.18
    volumes:
      - ./config/nodes/member3:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    command:
      - --networkid=1337
      - --nodiscover
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,admin
      - --datadir=/config/keys
      - --permissioned
      - --permissions-config=/permissions/permissioned-nodes.json
      - --maxpeers=50
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18


  # provides Web interface for viewing transactions, contracts, and accounts
  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31






  # Logging and Monitoring Stack
  prometheus: # Monitoring tool for metrics collection
    image: "prom/prometheus:v2.46.0"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml 
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  grafana: # Visualization tool for metrics
    image: "grafana/grafana:10.1.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.33

  loki: # Log aggregation system
    image: "grafana/loki:2.8.4"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  promtail: # Agent for collecting logs and sending them to Loki
    image: "grafana/promtail:2.8.4"
    volumes:
      - ./logs:/var/log
      - ./promtail/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35



networks:
  shared-net:
   external: true
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  splunk:
  ethlogger:
  prometheus:
  grafana:
  blockscoutpostgres: